# Generated by Django 3.1.1 on 2022-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorBackOffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='speciality',
            field=models.CharField(choices=[('allergists', 'Allergists'), ('diabetologist', 'Diabetologist'), ('dermatologist', 'Dermatologist'), ('cardiologist', 'Cardiologist'), ('urologist', 'Urologist'), ('dentist', 'Dentist'), ('generalist', 'Generalist'), ('psychiatrist', 'Psychiatrist'), ('radiologist', 'Radiologist')], default='generalist', max_length=40),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
