# Generated by Django 3.2.13 on 2022-04-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorBackOffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='bill',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctorBackOffice.service'),
        ),
    ]
