# Generated by Django 3.2.13 on 2022-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorBackOffice', '0002_auto_20220411_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(default=None, related_name='services', to='doctorBackOffice.Service'),
        ),
    ]
