# Generated by Django 3.2.13 on 2022-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorBackOffice', '0003_auto_20220411_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(default=None, related_name='service', to='doctorBackOffice.Service'),
        ),
    ]
