# Generated by Django 3.2.13 on 2022-04-12 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctorBackOffice', '0003_auto_20220411_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
