# Generated by Django 3.2.13 on 2022-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorBackOffice', '0004_auto_20220411_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(default=None, related_name='services', to='doctorBackOffice.Service'),
        ),
    ]
