# Generated by Django 3.2.13 on 2022-04-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorBackOffice', '0007_auto_20220412_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctorBackOffice.appointment'),
        ),
    ]
